MusicService/MusicService/Controllers/MvcUploaderTestController.cs
using System.Linq;
using System.Collections.Generic;
using System.Web.Mvc;
using MusicService.Models;
using MvcFileUploader;
using MvcFileUploader.Models;

namespace MusicService.Controllers
{
    public class MvcUploaderTestController : Controller
    {
        //
        // GET: /MvcUploaderTest/Demo

        public ActionResult Demo()
        {
            return View();
        }
        private UsersContext db = new UsersContext();

        public ActionResult UploadFile(int? entityId) // optionally receive values specified with Html helper
        {
            // here we can send in some extra info to be included with the delete url 
            var statuses = (List<ViewDataUploadFileResult>)TempData["statuses"];
            if (statuses==null)
                 statuses=new List<ViewDataUploadFileResult>();
            for (var i = 0; i < Request.Files.Count; i++ )
            {
                var st = FileSaver.StoreFile(x =>
                                                 {
                                                     x.File = Request.Files[i];
                                                     //note how we are adding an additional value to be posted with delete request
                                                     //and giving it the same value posted with upload
                                                     x.DeleteUrl = Url.Action("DeleteFile", new { entityId = entityId });
                                                     x.StorageDirectory = Server.MapPath("~/Content/uploads");
                                                     x.UrlPrefix = "/Content/uploads";

                                                 });
                CreateTrack(st.name, st.url); 
                statuses.Add(st);
            }             

            //statuses contains all the uploaded files details (if error occurs the check error property is not null or empty)
            //todo: add additional code to generate thumbnail for videos, associate files with entities etc
            
            //adding thumbnail url for jquery file upload javascript plugin
            //statuses.ForEach(x=>x.thumbnail_url=x.url+"?width=80&height=80"); // uses ImageResizer httpmodule to resize images from this url
            TempData["statuses"] = statuses;

            return Json(statuses);
        }

        public Track CreateTrack(string name, string fileUrl)
        {
            Track track = new Track(name, fileUrl);
            db.Tracks.Add(track);
            db.SaveChanges();
            return track;
        }

        public Track FindTrackByUrl(string fileUrl)
        {
            return db.Tracks.ToList().Find(x => x.FileName == fileUrl);
        }

        //here i am receving the extra info injected
        public ActionResult DeleteFile(int? entityId, string fileUrl)
        {
            Track track = FindTrackByUrl(fileUrl);
            if (track != null)
            {
                db.Tracks.Remove(track);
                db.SaveChanges();
            }
            var filePath = Server.MapPath("~" + fileUrl);

            if(System.IO.File.Exists(filePath))
                System.IO.File.Delete(filePath);

            return new HttpStatusCodeResult(200); // trigger success
        }

    }
}

MusicService/MusicService/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicService.Models;
using MvcFileUploader;
using MvcFileUploader.Models;

namespace MusicService.Controllers
{
    public class PostController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Post/

        public ActionResult Index()
        {
            return View(db.Posts.ToList());
        }

        //
        // GET: /Post/Details/5

        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Post/Create
        [Authorize]
        public ActionResult Create()
        {            
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        public ActionResult Create(Post post)
        {
            var statuses = new List<ViewDataUploadFileResult>();
            statuses = (List<ViewDataUploadFileResult>)TempData["statuses"];

            if (ModelState.IsValid)
            {
                post.User = db.UserProfiles.Single(u => u.UserName == User.Identity.Name);

                db.SaveChanges();

                foreach (var status in statuses)
                {
                    Track track = db.Tracks.ToList().Find(x => x.FileName == status.url);
                    post.Tracks.Add(track);
                    //TracksInPost tracks = new TracksInPost();
                }
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }


        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Post post)
        {
            return RedirectToAction("Index");
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        public Track FindTrackByUrl(string fileUrl)
        {
            return db.Tracks.ToList().Find(x => x.FileName == fileUrl);
        }
        //here i am receving the extra info injected
        public ActionResult DeleteFile(int? entityId, string fileUrl)
        {

            Track track = FindTrackByUrl(fileUrl);
            if (track != null)
            {
                db.Tracks.Remove(track);
                db.SaveChanges();
            }
            var filePath = Server.MapPath("~" + fileUrl);
            if (System.IO.File.Exists(filePath))
                System.IO.File.Delete(filePath);
            return new HttpStatusCodeResult(200); // trigger success
        }
    }
}

MusicService/MusicService/Views/Post/Create.cshtml
@model MusicService.Models.Post
@using MusicService.Models
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    TempData["statuses"] = new List<MvcFileUploader.Models.ViewDataUploadFileResult>(); 
}


<style type="text/css">
    #dropZone {
        background: gray;
        border: black dashed 3px;
        width: auto;
        padding: 50px;
        text-align: center;
        color: white;
    }
</style>
        <legend>Post</legend>

        <!-- file upload modal dialog -->
        <div class="modal hide" id="dlgFileUpload" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-body"></div>
        </div>

        <div class="well">
            <legend>Upload Inline</legend>        
            @Html.Partial("_MvcFileupload", new MvcFileUploader.Models.FileUploadConfig() { FileTypes = @"/(\.|\/)(mp3|flac)$/i", MaxFileSizeInBytes = 50000000, UploadUrl = Url.Action("UploadFile", "MvcUploaderTest") })
            <div id="dropZone">Drop your files here</div>
        </div>
    @using (Html.BeginForm("Create", "Post", FormMethod.Post))
    {
    <fieldset>
        <div class="editor-label">
            @Html.LabelFor(model => model.Message)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Message, new { style = "width: 70%;height: 100px;" })
            @Html.ValidationMessageFor(model => model.Message)
        </div>
        
        <input class="btn btn-inverse" type="submit" value="Post" />
        
        
    </fieldset>
    }
    
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MusicService/MusicService/Views/Post/Delete.cshtml
@model MusicService.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Post</legend>

    <h5>
         @Html.DisplayNameFor(model => model.Message)
    </h5>
    <div class="display-field">
        @Html.DisplayFor(model => model.Message)
    </div>

    <h5>
         @Html.DisplayNameFor(model => model.Likes)
    </h5>
    <div class="display-field">
        @Html.DisplayFor(model => model.Likes.Count)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input  class="btn btn-inverse" type="submit" value="Delete" /> |
        <button class="btn btn-inverse"> @Html.ActionLink("Back to List", "Index")</button> 
        
    </p>
}

MusicService/MusicService/Views/Post/Details.cshtml
@model MusicService.Models.Post
@using MusicService.Models
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
@Html.Partial("_Player")
<div class="row">
    <div class="span8">
        <div class="row">
            <div class="span8">
                <h4><strong>Post</></strong></h4>
            </div>
        </div>
        <div class="row">
            <div class="span2">

                @{UsersContext db = new UsersContext();
                  var tracks = Model.Tracks;
                  foreach (var track in tracks)
                  {            
                    <div class="ui360 ui360-vis">
                        <a href="~/@Uri.EscapeDataString(track.FileName).ToString()">@Html.DisplayFor(modelItem => track.Name)</a>
                    </div>
                  }
                }
                <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">Action
    <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        @{ var routevalues = new { id = Model.PostId };  
                            <li>@Html.ActionLink("Edit", "Edit", routevalues)</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Delete", "Delete", routevalues)</li>                             
                        }
                    </ul>
                </div>


            </div>
            <div class="span6">
                <p>
                    @Model.Message
                </p>
            </div>
        </div>
        <div class="row">
            <div class="span8">
                <p></p>
                <p>
                    <i class="icon-user"></i>by <a href="#">@Model.User.UserName</a>
                    | <i class="icon-thumbs-up"></i><a>&nbsp; @Model.Likes.Count &nbsp;</a>
                    | &nbsp;&nbsp;&nbsp;&nbsp; <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-thumbs-up"></i></a>
                </p>
            </div>
        </div>
    </div>
</div>
<hr>

MusicService/MusicService/Views/Post/Edit.cshtml
@model MusicService.Models.Post

@{
    ViewBag.Title = "Edit2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit2</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.PostId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Message)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Message)
            @Html.ValidationMessageFor(model => model.Message)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MusicService/MusicService/Views/Post/Index.cshtml
@model IEnumerable<MusicService.Models.Post>
@using MusicService.Models
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.Partial("_Player")
<h2 style="margin-top: 1em">Music</h2>
<button class="btn btn-inverse">@Html.ActionLink("Create New", "Create", "Post")</button>
@foreach (var post in Model)
{
    <div class="row">
        <div class="span8">
            <div class="row">
                <div class="span8">
                    <h4><strong>@Html.ActionLink("Open", "Details", new { id = post.PostId })</strong></h4>
                </div>
            </div>
            <div class="row">
                <div class="span6">
                    <p>
                        @post.Message
                    </p>
                </div>
                <div class="span8">

                    @{UsersContext db = new UsersContext();
                      var tracks = post.Tracks;
                      foreach (var track in tracks)
                      {            
                        <div class="ui360">
                            <a href=@Uri.EscapeDataString(track.FileName)>@Html.DisplayFor(modelItem => track.Name)</a>
                        </div>
                        <a href="~/@Uri.EscapeDataString(track.FileName).ToString()" title=@track.Name rel="" download=@track.Name><i class="icon-hdd"></i>Save</a>

                      }
                    }
                </div>
            </div>
            <div class="row">
                <div class="span8">
                    <p></p>
                    <p>
                        <i class="icon-user"></i>by <a href="#">@post.User.UserName</a>
                        |  <i class="icon-hdd"></i>@Html.ActionLink("Details", "Details", new { id = post.PostId })
                        | <i class="icon-thumbs-up"></i><a>&nbsp; @post.Likes.Count &nbsp;</a>
                        | &nbsp;&nbsp;&nbsp;&nbsp; <a href="#" class="btn btn-inverse disabled"><i class="icon-white icon-thumbs-up"></i></a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <br />
}