MusicService/MusicService/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicService.Models;


namespace MusicService.Controllers
{
    public class MusicController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Music/

        public ActionResult Index()
        {
            return View(db.Tracks.ToList());
        }

        //
        // GET: /Music/Details/5

        public ActionResult Details(int id = 0)
        {
            Track track = db.Tracks.Find(id);
            if (track == null)
            {
                return HttpNotFound();
            }
            return View(track);
        }



        //
        // GET: /Music/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Track track = db.Tracks.Find(id);
            if (track == null)
            {
                return HttpNotFound();
            }
            return View(track);
        }

        //
        // POST: /Music/Edit/5

        [HttpPost]
        public ActionResult Edit(Track track)
        {
            if (ModelState.IsValid)
            {
                db.Entry(track).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(track);
        }

        //
        // GET: /Music/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Track track = db.Tracks.Find(id);
            if (track == null)
            {
                return HttpNotFound();
            }
            return View(track);
        }

        //
        // POST: /Music/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Track track = db.Tracks.Find(id);
            var filePath = Server.MapPath(track.FileName);
            if (System.IO.File.Exists(filePath))
                System.IO.File.Delete(filePath);
            db.Tracks.Remove(track);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MusicService/MusicService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>@ViewBag.Title</title>    
    
    <script type="text/javascript" src="/Scripts/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/Scripts/jquery-ui-1.8.24.min.js"></script>
    <script src="@Url.Content("~/Scripts/jquery.filedrop.js")" type="text/javascript"></script>       
    <script type="text/javascript" src="/Scripts/bootstrap.js"></script>  
    <link href="/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />      
    
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>    
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">MusicService</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                 <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("MusicList", "Index", "Music")</li>
                <li>@Html.ActionLink("Post", "Index", "Post")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
              <div class="navbar-form pull-right">
                     <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
            </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        
        @RenderBody()

    </div> <!-- /container -->    
        
    
       
    @RenderSection("Scripts", false)
</body>
</html>

MusicService/MusicService/Views/Shared/_MvcFileUpload.cshtml
@model MvcFileUploader.Models.FileUploadConfig
@{
    var formId = "fileupload" + (new Random()).Next(1, 10);
    var fileInputId = "file" + (new Random()).Next(11, 20);
}
        
<!-- file upload modal dialog -->

    <form id="@formId" action="@Model.UploadUrl" method="POST" enctype="multipart/form-data">
        
        <div class="modal-header">  
            <div class="btn-group fileupload-buttonbar">
                <span class="btn btn-inverse fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Add files...</span>
                    <input type="file" name="@fileInputId" multiple>
                </span>
                <button type="submit" class="btn btn-inverse">
                    <i class="icon-upload icon-white"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-inverse">
                    <i class="icon-ban-circle icon-white"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-inverse">
                    <i class="icon-trash icon-white"></i>
                    <span>Delete</span>
                </button>
                @if(Model.IsDialog && !String.IsNullOrEmpty(Model.ReturnUrl))
                {
                    <a href='@Model.ReturnUrl' type="button" class="pull-right close">&times;</a>
                } 
                else if(Model.IsDialog && String.IsNullOrEmpty(Model.ReturnUrl))
                {
                    <a href='#' type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</a>
                } 
            </div>
            <!-- The global progress information -->
            <div class="fileupload-progress fade">                
                <!-- The extended global progress information -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <div class="modal-body">
            <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
        </div>        
        
        <!-- Additional values to be posted -->
        @foreach(var postItem in Model.PostValuesWithUpload)
        {
            @Html.Hidden(postItem.Key, postItem.Value)
        }
    </form>

    
    
<!-- The global progress bar -->
<div class="progress progress-success progress-striped active fade">
    <div class="bar" style="width:0%;"></div>
</div>
<!-- The loading indicator is shown during image processing -->
<div class="fileupload-loading">loading..</div>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td>
                <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
            </td>
            <td class="start">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-inverse">
                    <i class="icon-upload icon-white"></i>
                    <span>{%=locale.fileupload.start%}</span>
                </button>
            {% } %}</td>
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-inverse">
                <i class="icon-ban-circle icon-white"></i>
                <span>{%=locale.fileupload.cancel%}</span>
            </button>
        {% } %}</td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
            <td class="preview">{% if (file.thumbnail_url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete">
            <button class="btn btn-inverse" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <i class="icon-trash icon-white"></i>
                <span>{%=locale.fileupload.destroy%}</span>
            </button>
            <input type="checkbox" name="delete" value="1">
        </td>
    </tr>
{% } %}
</script>


<!-- Jquery File Upload-->
<script type="text/javascript" src="/Scripts/mvcfileupload/tmpl.min.js"></script>
<script type="text/javascript" src="/Scripts/mvcfileupload/mvcfileupload.js"></script>


<link href="/Content/mvcfileupload/mvcfileupload.css" rel="stylesheet" type="text/css"/>

<script type="text/javascript">
    'use strict';

    
        // Initialize the jQuery File Upload widget:
        $('#@(formId)').fileupload();

        $('#@(formId)').fileupload('option', {
            maxFileSize: @Model.MaxFileSizeInBytes,
            resizeMaxWidth: 1920,
            resizeMaxHeight: 1200,
            acceptFileTypes: @Model.FileTypes
        });
    
    
</script>

MusicService/MusicService/Views/Shared/_MvcFileUploaderLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>    
    
    <script type="text/javascript" src="/Scripts/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/Scripts/jquery-ui-1.8.24.min.js"></script>
            
            
    <link href="/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />      
    
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>    
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <h3>Mvc File uploder Demo</h3>
        
        @RenderBody()

    </div> <!-- /container -->    
        
    
    <script type="text/javascript" src="/Scripts/mvcfileupload/bootstrap.js"></script>    
    @RenderSection("Scripts", false)
</body>
</html>

MusicService/MusicService/Views/Shared/_Player.cshtml
<<!-- demo, make the fonts nicer etc. -->
<link rel="stylesheet" type="text/css" href="/content/index.css" />
<!-- soundManager.useFlashBlock: related CSS -->
<link rel="stylesheet" type="text/css" href="/content/flashblock/flashblock.css" />

<!-- required -->
<link rel="stylesheet" type="text/css" href="/content/360player.css" />
<link rel="stylesheet" type="text/css" href="/content/360player-visualization.css" />

<!-- special IE-only canvas fix -->
<!--[if IE]><script type="text/javascript" src="script/excanvas.js"></script><![endif]-->

<!-- Apache-licensed animation library -->
<script type="text/javascript" src="/scripts/berniecode-animator.js"></script>

<!-- the core stuff -->
<script type="text/javascript" src="/scripts/soundmanager2.js"></script>
<script type="text/javascript" src="/scripts/360player.js"></script>

<script type="text/javascript">

    soundManager.setup({
        // path to directory containing SM2 SWF
        url: '/content/swf/'
    });
    threeSixtyPlayer.config.scaleFont = (navigator.userAgent.match(/msie/i) ? false : true);
    threeSixtyPlayer.config.showHMSTime = true;
    // enable some spectrum stuffs
    threeSixtyPlayer.config.useWaveformData = true;
    threeSixtyPlayer.config.useEQData = true;
    // enable this in SM2 as well, as needed
    if (threeSixtyPlayer.config.useWaveformData) {
        soundManager.flash9Options.useWaveformData = true;
    }
    if (threeSixtyPlayer.config.useEQData) {
        soundManager.flash9Options.useEQData = true;
    }
    if (threeSixtyPlayer.config.usePeakData) {
        soundManager.flash9Options.usePeakData = true;
    }
    if (threeSixtyPlayer.config.useWaveformData || threeSixtyPlayer.flash9Options.useEQData || threeSixtyPlayer.flash9Options.usePeakData) {
        // even if HTML5 supports MP3, prefer flash so the visualization features can be used.
        soundManager.preferFlash = true;
    }
    // favicon is expensive CPU-wise, but can be used.
    if (window.location.href.match(/hifi/i)) {
        threeSixtyPlayer.config.useFavIcon = true;
    }
    if (window.location.href.match(/html5/i)) {
        // for testing IE 9, etc.
        soundManager.useHTML5Audio = true;
    }

</script>

<!-- DEMO only, customization UI: Yahoo! YUI colorpicker stuff -->
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/slider/assets/skins/sam/slider.css" />
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/colorpicker/assets/skins/sam/colorpicker.css" />
<script type="text/javascript" src="http://yui.yahooapis.com/2.7.0/build/yahoo-dom-event/yahoo-dom-event.js"></script>
<script type="text/javascript" src="http://yui.yahooapis.com/2.7.0/build/animation/animation-min.js"></script>
<script type="text/javascript" src="http://yui.yahooapis.com/2.7.0/build/dragdrop/dragdrop-min.js"></script>
<script type="text/javascript" src="http://yui.yahooapis.com/2.7.0/build/slider/slider-min.js"></script>
<script type="text/javascript" src="http://yui.yahooapis.com/2.7.0/build/element/element-min.js"></script>
<script type="text/javascript" src="http://yui.yahooapis.com/2.7.0/build/colorpicker/colorpicker-min.js"></script>

<link rel="stylesheet" type="text/css" href="demo.css" />
<style type="text/css">
    body
    {
        background-image: none;
    }

    #left h2
    {
        padding-top: 0px;
        margin-bottom: 0.25em;
        color: #666;
    }

    pre.block
    {
        margin-top: 0.5em;
    }

    /* special case */

    #left
    {
        width: auto;
        max-width: 100%;
    }

    .ui360 span
    {
        vertical-align: top;
    }
</style>

<!-- demo configuration stuff, you don't need this -->
<link rel="stylesheet" type="text/css" href="/content/demo-slider-controls.css" />
<script type="text/javascript" src="/scripts/demo-slider-controls.js"></script>

<body>

    <div id="left">
        <div id="config-ui" style="clear: both; position: relative; max-width: 1110px; margin-top: 1em; display: none">
            <div style="position: relative">
                <form action="#" method="get">
                    <div id="controls">
                        <div class="checkbox">
                            <div>
                                <input id="use-waveform" type="checkbox" checked="checked" title="Enable waveform feature." onclick="controller.updateExample(); controller.updateExampleCode()" value="Apply" />
                                Waveform
			    <input id="disabled-1" type="checkbox" title="Enable EQ (spectrum) feature." onclick="controller.updateExample(); controller.updateExampleCode()" value="Apply" style="margin-left: 1em" checked="checked" />
                                EQ
			    <input type="checkbox" name="use-amplifier" id="use-amplifier" checked="checked" onclick="controller.updateExample(); controller.updateExampleCode()" style="margin-left: 1em">
                                Amplifier
                            </div>
                        </div>
                        <div style="clear: left"></div>
                        <dl class="col">
                            <dt>Circle Diameter</dt>
                            <dd class="title">Size</dd>
                            <dd>1-256</dd>
                            <dd class="control">
                                <div class="bar" title="Click to move here"></div>
                                <div class="slider" title="Size of circle"></div>
                            </dd>

                            <dt>Waveform Thickness</dt>
                            <dd class="title">thickness</dd>
                            <dd>1-100</dd>
                            <dd class="control">
                                <div class="bar" title="Click to move here"></div>
                                <div class="slider" title="Thickness of line"></div>
                            </dd>

                            <dt>Wave Downsample</dt>
                            <dd class="title">(Scale)</dd>
                            <dd>1-16</dd>
                            <dd class="control">
                                <div class="bar" title="Click to move here"></div>
                                <div class="slider" title="Amount to downsample waveform data by"></div>
                            </dd>

                            <dt>EQ Thickness</dt>
                            <dd class="title">thickness</dd>
                            <dd>1-50</dd>
                            <dd class="control">
                                <div class="bar" title="Click to move here"></div>
                                <div class="slider" title="Thickness of line"></div>
                            </dd>

                            <dt>EQ Downsample</dt>
                            <dd class="title">(Scale)</dd>
                            <dd>1-16</dd>
                            <dd class="control">
                                <div class="bar" title="Click to move here"></div>
                                <div class="slider" title="Amount to downsample EQ data by"></div>
                            </dd>

                            <dt>Ring Thickness</dt>
                            <dd class="title">(Scale)</dd>
                            <dd>1-200</dd>
                            <dd class="control">
                                <div class="bar" title="Click to move here"></div>
                                <div class="slider" title="Scale factor for the ring width"></div>
                            </dd>

                        </dl>

                        <div id="options" class="col">

                            <div>
                                Waveform position:
			    <input type="radio" name="waveform-inside" id="waveform-inside" value="true" checked="checked" onclick="controller.updateExample(); controller.updateExampleCode()">
                                Inside |
                                <input type="radio" name="waveform-inside" id="waveform-inside" value="false" onclick="    controller.updateExample(); controller.updateExampleCode()">
                                Outside
                            </div>

                            <div>
                                EQ position:
			    <input type="radio" name="eq-inside" id="eq-inside" value="true" onclick="controller.updateExample(); controller.updateExampleCode()">
                                Inside |
                                <input type="radio" name="eq-inside" id="eq-inside" value="false" checked="checked" onclick="    controller.updateExample(); controller.updateExampleCode()">
                                Outside
                            </div>

                            <div>
                                Waveform color:
				<input type="text" name="waveform-color" id="waveform-color" value="#000000" onclick="createCP(this, setWaveformColor)" />
                            </div>

                            <div>
                                EQ color:
				<input type="text" name="eq-color" id="eq-color" value="#000000" onclick="createCP(this, setEQColor)" />
                            </div>

                            <div>
                                Loaded ring color:
				<input type="text" name="loaded-ring-color" id="loaded-ring-color" value="#000000" onclick="createCP(this, setLoadedRingColor)" />
                            </div>

                            <div>
                                Progress ring color:
				<input type="text" name="progress-ring-color" id="progress-ring-color" value="#000000" onclick="createCP(this, setProgressRingColor)" />
                            </div>

                            <div>
                                Background ring color:
				<input type="text" name="bg-ring-color" id="bg-ring-color" value="#000000" onclick="createCP(this, setBackgroundRingColor)" />
                            </div>

                            <p class="compact">
                                <input type="button" onclick="controller.randomize()" value="Randomize controls" title="Assign random control values" style="font-size: x-small" />
                            </p>
                </form>

            </div>

            <div id="cp-container">
                <!-- color picker stuff goes here -->
            </div>

            <div id="config-code-block" style="float: right; display: inline; margin-left: 1em; margin-top: -0.7em">
                <!--
			<pre id="config-link" class="block"><code style="cursor:pointer" onclick="document.getElementById('config-link').style.display='none';document.getElementById('config-pre-block').style.display='block';return false"> [click to show code]                 </code></pre>
		-->
                <pre id="config-pre-block" class="block"><code id="config-code">Code goes here</code></pre>
            </div>

        </div>

    </div>
    </div>
    </body>